### ISSUE TITLE
Add comments about OsrEnabled

### ISSUE THREAD

**Issue by Takoooooo** [OutSystems/WebView#167]
I haven't found any info about it and accidentally set it to true and the browser started to overlap other controls, become more laggy, navigation worked less responsive. Add some info about it, please

**Comment by joaompneves** [comment]
Documentation is definitely onde of the areas that needs improvements.
OSR stands for Off-Screen-Rendering... its a rendering mode (provided by CEF) that allows a seamless integration with other surfaces (graphical frameworks). In this mode the browser renders an image and all the user interactions are forwarded to the browser. You can easily place other widgets (Avalonia or WPF) above this image. This is usually slower.
Standard mode is a mode where the browser renders its viewport inside a window. In this mode you cannot easily place widgets on top of the browser, because the viewport airspace area is owned by the browser. This is the "normal" mode used by chromium and the fastest.
