### ISSUE TITLE
Doesn't work on Avalonia version 11.0.0-preview4

### ISSUE THREAD

**Issue by Spankusina** [OutSystems/WebView#287]
When running on Avalonia version 11 exception thrown: "Could not load file or assembly 'Avalonia.Styling, Version=0.10.17.0"
Are there options to fix this?

 Installed: WebViewControl-Avalonia 2.106.0-preview1

**Comment by joaompneves** [comment]
Hi,

In order to run on a new Avalonia major version [CefGlue](https://github.com/OutSystems/CefGlue) (the underlying browser component) also needs to be updated to that same Avalonia version. WebView Avalonia version upgrades only work when there are no breaking changes (usually on minors). Since Avalonia 11 is still on preview we migrated yet.
