### ISSUE TITLE
[request] routed events implementation

### ISSUE THREAD

**Issue by supermomonga** [OutSystems/WebView#354]
I think It's handy if there are Routed Events implementations.

Docs:

- WPF: https://learn.microsoft.com/en-us/dotnet/desktop/wpf/events/routed-events-overview?view=netdesktop-8.0#how-routed-events-are-implemented
- Avalonia: https://docs.avaloniaui.net/docs/concepts/input/routed-events#how-routed-events-are-implemented

**Comment by joaompneves** [comment]
At this point introducing Routed Events is not very convenient. Changing to routed events would cause breaking changes and adding new events would pollute the API. We opted for not doing so because Routed Events are tied to the UI framework, and with standard CLR events we can share the same event signatures between UI frameworks.
You can always create a webview wrapper and expose as you wish.
